{% set name = "beamngpy" %}
{% set version = "1.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beamngpy-{{ version }}.tar.gz
  sha256: af1bf20d0c3683ec16cb4d5a219340e108bb39566f88e1cb18b3156fe80c1bec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - jinja2
    - matplotlib-base
    - msgpack-python
    - numpy
    - pillow
    - pyopengl
    - python >=3.6
    - scipy

test:
  imports:
    - beamngpy
    - beamngpy.sensors
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BeamNG/BeamNGpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python API to interact with BeamNG.tech.
  doc_url: https://beamngpy.readthedocs.io
  dev_url: https://github.com/BeamNG/BeamNGpy

extra:
  recipe-maintainers:
    - aivora-beamng
