{% set name = "beamngpy" %}
{% set version = "1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/beamngpy-{{ version }}.tar.gz
  sha256: 5f5707fedcdae0c6f1cabdbfe839d6cb282272aca7935d61eea40c11caec12da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click
    - jinja2
    - matplotlib-base
    - msgpack-python
    - numpy
    - pillow
    - pyopengl
    - python >=3.6
    - scipy

test:
  imports:
    - beamngpy
    - beamngpy.sensors
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BeamNG/BeamNGpy
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python API to interact with BeamNG.tech.
  doc_url: https://beamngpy.readthedocs.io
  dev_url: https://github.com/BeamNG/BeamNGpy

extra:
  recipe-maintainers:
    - aivora-beamng
